version: '3'

services:
  postgres:
    image: 'postgres'
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gobook
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always